export const bibleBooks = {
	Gênesis: 'Gên',
	Êxodo: 'Êx',
	Levítico: 'Le',
	Números: 'Núm',
	Deuteronômio: 'De',
	Josué: 'Jos',
	Juízes: 'Jz',
	Rute: 'Ru',
	'1 Samuel': '1Sa',
	'2 Samuel': '2Sa',
	'1 Reis': '1Rs',
	'2 Reis': '2Rs',
	'1 Crônicas': '1Cr',
	'2 Crônicas': '2Cr',
	Esdras: 'Esd',
	Neemias: 'Ne',
	Ester: 'Est',
	Jó: 'Jó',
	Salmos: 'Sal',
	Provérbios: 'Pr',
	Eclesiastes: 'Ec',
	'Cântico de Salomão': 'Cân',
	Isaías: 'Is',
	Jeremias: 'Je',
	Lamentações: 'La',
	Ezequiel: 'Ez',
	Daniel: 'Da',
	Oseias: 'Os',
	Joel: 'Jl',
	Amós: 'Am',
	Obadias: 'Ob',
	Jonas: 'Jon',
	Miqueias: 'Miq',
	Naum: 'Na',
	Habacuque: 'Hab',
	Sofonias: 'Sof',
	Ageu: 'Ag',
	Zacarias: 'Za',
	Malaquias: 'Mal',
	Mateus: 'Mt',
	Marcos: 'Mr',
	Lucas: 'Lu',
	João: 'Jo',
	Atos: 'At',
	Romanos: 'Ro',
	'1 Coríntios': '1Co',
	'2 Coríntios': '2Co',
	Gálatas: 'Gál',
	Efésios: 'Ef',
	Filipenses: 'Fil',
	Colossenses: 'Col',
	'1 Tessalonicenses': '1Te',
	'2 Tessalonicenses': '2Te',
	'1 Timóteo': '1Ti',
	'2 Timóteo': '2Ti',
	Tito: 'Tit',
	Filêmon: 'Flm',
	Hebreus: 'He',
	Tiago: 'Tg',
	'1 Pedro': '1Pe',
	'2 Pedro': '2Pe',
	'1 João': '1Jo',
	'2 João': '2Jo',
	'3 João': '3Jo',
	Judas: 'Ju',
	Apocalipse: 'Ap'
};
